//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_jobproject
{
    using System;
    using System.Collections.Generic;
    
    public partial class comp_reg
    {
        public int comp_id { get; set; }
        public string comp_name { get; set; }
        public string comp_email { get; set; }
        public string comp_number { get; set; }
        public string comp_address { get; set; }
        public string comp_website { get; set; }
    }
}
