//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_jobproject
{
    using System;
    using System.Collections.Generic;
    
    public partial class job_tab
    {
        public int job_id { get; set; }
        public string job_tittle { get; set; }
        public string job_desc { get; set; }
        public string job_skills { get; set; }
        public int comp_id { get; set; }
        public System.DateTime closing_date { get; set; }
        public string status { get; set; }
        public Nullable<int> job_exp { get; set; }
    }
}
