//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_jobproject
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_reg
    {
        public int id { get; set; }
        public string name { get; set; }
        public int age { get; set; }
        public string address { get; set; }
        public string email { get; set; }
        public string photo { get; set; }
        public string phone { get; set; }
        public string skills { get; set; }
        public string exp { get; set; }
        public string qualification { get; set; }
    }
}
